// Central definition of every clinical module exposed by the backend.
// Each config drives the generic list page, form, and table renderer.

const today = () => new Date().toISOString().slice(0, 10)

export const entities = {
  pets: {
    key: 'pets',
    label: 'Pets',
    singular: 'Pet',
    endpoint: '/pets',
    icon: 'paw',
    description: 'Registered patients and their owner details.',
    columns: [
      { key: 'petName', label: 'Pet' },
      { key: 'species', label: 'Species' },
      { key: 'breed', label: 'Breed' },
      { key: 'age', label: 'Age' },
      { key: 'ownerName', label: 'Owner' },
      { key: 'ownerPhone', label: 'Phone' },
      { key: 'active', label: 'Active', type: 'badge' },
    ],
    fields: [
      { name: 'petName', label: 'Pet name', type: 'text', required: true },
      { name: 'species', label: 'Species', type: 'text', required: true, placeholder: 'Dog, Cat, Rabbit…' },
      { name: 'breed', label: 'Breed', type: 'text', required: true },
      { name: 'age', label: 'Age (years)', type: 'number', required: true, min: 0 },
      { name: 'weight', label: 'Weight (kg)', type: 'number', required: true, step: '0.1', min: 0 },
      { name: 'gender', label: 'Gender', type: 'select', required: true, options: ['Male', 'Female', 'Unknown'] },
      { name: 'color', label: 'Color', type: 'text', required: true },
      { name: 'dateOfBirth', label: 'Date of birth', type: 'date', required: true },
      { name: 'microchipNumber', label: 'Microchip number', type: 'text', required: true },
      { name: 'ownerName', label: 'Owner name', type: 'text', required: true },
      { name: 'ownerEmail', label: 'Owner email', type: 'email', required: true },
      { name: 'ownerPhone', label: 'Owner phone', type: 'tel', required: true, placeholder: '10-digit mobile number' },
      { name: 'address', label: 'Address', type: 'textarea', required: true },
    ],
  },

  consultants: {
    key: 'consultants',
    label: 'Consultant Availability',
    singular: 'Availability Slot',
    endpoint: '/consultants',
    icon: 'calendar',
    description: 'Consultant schedules and appointment capacity.',
    columns: [
      { key: 'consultantCode', label: 'Code' },
      { key: 'consultantName', label: 'Consultant' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'availableDate', label: 'Date' },
      { key: 'startTime', label: 'Start' },
      { key: 'endTime', label: 'End' },
      { key: 'availabilityStatus', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'consultantCode', label: 'Consultant code', type: 'text', required: true },
      { name: 'consultantName', label: 'Consultant name', type: 'text', required: true },
      { name: 'specialization', label: 'Specialization', type: 'text', required: true },
      { name: 'qualification', label: 'Qualification', type: 'text' },
      { name: 'availableDay', label: 'Day of week', type: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
      { name: 'availableDate', label: 'Available date', type: 'date', required: true, default: today },
      { name: 'startTime', label: 'Start time', type: 'time', required: true },
      { name: 'endTime', label: 'End time', type: 'time', required: true },
      { name: 'maxAppointments', label: 'Max appointments', type: 'number', min: 0 },
      { name: 'bookedAppointments', label: 'Booked appointments', type: 'number', min: 0, default: () => 0 },
      { name: 'availabilityStatus', label: 'Availability status', type: 'select', required: true, options: ['AVAILABLE', 'FULLY_BOOKED', 'ON_LEAVE', 'UNAVAILABLE'] },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },

  emergencyContacts: {
    key: 'emergencyContacts',
    label: 'Emergency Contacts',
    singular: 'Emergency Contact',
    endpoint: '/emergency-contacts',
    icon: 'phone',
    description: 'Who to call first when a case turns urgent.',
    columns: [
      { key: 'contactName', label: 'Contact' },
      { key: 'relationship', label: 'Relationship' },
      { key: 'petName', label: 'Pet' },
      { key: 'ownerName', label: 'Owner' },
      { key: 'mobileNumber', label: 'Mobile' },
      { key: 'active', label: 'Active', type: 'badge' },
    ],
    fields: [
      { name: 'contactName', label: 'Contact name', type: 'text', required: true },
      { name: 'relationship', label: 'Relationship', type: 'text', required: true, placeholder: 'Spouse, Neighbor, Vet…' },
      { name: 'petName', label: 'Pet name', type: 'text' },
      { name: 'ownerName', label: 'Owner name', type: 'text', required: true },
      { name: 'mobileNumber', label: 'Mobile number', type: 'tel', required: true },
      { name: 'alternateNumber', label: 'Alternate number', type: 'tel' },
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'address', label: 'Address', type: 'textarea', required: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  policies: {
    key: 'policies',
    label: 'Insurance Policies',
    singular: 'Insurance Policy',
    endpoint: '/policies',
    icon: 'shield',
    description: 'Active coverage for every enrolled pet.',
    columns: [
      { key: 'policyNumber', label: 'Policy #' },
      { key: 'providerName', label: 'Provider' },
      { key: 'petName', label: 'Pet' },
      { key: 'ownerName', label: 'Owner' },
      { key: 'endDate', label: 'Expires' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'policyNumber', label: 'Policy number', type: 'text', required: true },
      { name: 'providerName', label: 'Provider name', type: 'text', required: true },
      { name: 'policyType', label: 'Policy type', type: 'select', required: true, options: ['Accident Only', 'Illness Only', 'Comprehensive', 'Wellness'] },
      { name: 'petName', label: 'Pet name', type: 'text', required: true },
      { name: 'ownerName', label: 'Policy holder name', type: 'text', required: true },
      { name: 'startDate', label: 'Start date', type: 'date', required: true, default: today },
      { name: 'endDate', label: 'End date', type: 'date', required: true },
      { name: 'coverageAmount', label: 'Coverage amount', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'premiumAmount', label: 'Premium amount', type: 'number', required: true, min: 0, step: '0.01' },
      { name: 'status', label: 'Policy status', type: 'select', required: true, options: ['ACTIVE', 'EXPIRED', 'CANCELLED', 'PENDING'] },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },

  therapy: {
    key: 'therapy',
    label: 'Therapy Progress',
    singular: 'Therapy Session',
    endpoint: '/therapy',
    icon: 'heart',
    description: 'Session-by-session progress for ongoing therapy plans.',
    columns: [
      { key: 'therapyId', label: 'Therapy ID' },
      { key: 'patientName', label: 'Patient' },
      { key: 'therapyType', label: 'Type' },
      { key: 'sessionNumber', label: 'Session #' },
      { key: 'progressStatus', label: 'Progress', type: 'badge' },
      { key: 'nextSessionDate', label: 'Next session' },
    ],
    fields: [
      { name: 'therapyId', label: 'Therapy ID', type: 'text', required: true },
      { name: 'patientName', label: 'Patient name', type: 'text', required: true },
      { name: 'consultantName', label: 'Consultant name', type: 'text', required: true },
      { name: 'therapyType', label: 'Therapy type', type: 'text', required: true },
      { name: 'sessionNumber', label: 'Session number', type: 'number', required: true, min: 1 },
      { name: 'sessionDate', label: 'Session date', type: 'date', required: true, default: today },
      { name: 'progressStatus', label: 'Progress status', type: 'select', required: true, options: ['IMPROVING', 'STABLE', 'DECLINING', 'COMPLETED'] },
      { name: 'therapistNotes', label: 'Therapist notes', type: 'textarea', required: true },
      { name: 'patientFeedback', label: 'Patient feedback', type: 'textarea' },
      { name: 'nextAction', label: 'Next action', type: 'text' },
      { name: 'nextSessionDate', label: 'Next session date', type: 'date', required: true },
    ],
  },

  treatments: {
    key: 'treatments',
    label: 'Treatment Records',
    singular: 'Treatment Record',
    endpoint: '/treatments',
    icon: 'stethoscope',
    description: 'Diagnoses, prescriptions, and follow-up visits.',
    columns: [
      { key: 'treatmentId', label: 'Treatment ID' },
      { key: 'petName', label: 'Pet' },
      { key: 'ownerName', label: 'Owner' },
      { key: 'veterinarianName', label: 'Veterinarian' },
      { key: 'diagnosis', label: 'Diagnosis' },
      { key: 'treatmentStatus', label: 'Status', type: 'badge' },
    ],
    fields: [
      { name: 'treatmentId', label: 'Treatment ID', type: 'text', required: true },
      { name: 'petName', label: 'Pet name', type: 'text' },
      { name: 'ownerName', label: 'Owner name', type: 'text', required: true },
      { name: 'veterinarianName', label: 'Veterinarian name', type: 'text', required: true },
      { name: 'diagnosis', label: 'Diagnosis', type: 'textarea', required: true },
      { name: 'treatmentType', label: 'Treatment type', type: 'text', required: true },
      { name: 'prescription', label: 'Prescription', type: 'textarea', required: true },
      { name: 'treatmentDate', label: 'Treatment date', type: 'date', required: true, default: today },
      { name: 'nextVisitDate', label: 'Next visit date', type: 'date', required: true },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
      { name: 'treatmentStatus', label: 'Treatment status', type: 'select', required: true, options: ['ONGOING', 'COMPLETED', 'FOLLOW_UP_REQUIRED', 'CANCELLED'] },
    ],
  },

  wellness: {
    key: 'wellness',
    label: 'Wellness Assessments',
    singular: 'Wellness Assessment',
    endpoint: '/wellness',
    icon: 'sparkle',
    description: 'Mental and physical wellbeing scores over time.',
    columns: [
      { key: 'assessmentId', label: 'Assessment ID' },
      { key: 'patientName', label: 'Patient' },
      { key: 'assessmentDate', label: 'Date' },
      { key: 'overallStatus', label: 'Status', type: 'badge' },
      { key: 'nextAssessmentDate', label: 'Next assessment' },
    ],
    fields: [
      { name: 'assessmentId', label: 'Assessment ID', type: 'text', required: true },
      { name: 'patientName', label: 'Patient name', type: 'text', required: true },
      { name: 'consultantName', label: 'Consultant name', type: 'text', required: true },
      { name: 'assessmentDate', label: 'Assessment date', type: 'date', required: true, default: today },
      { name: 'stressLevel', label: 'Stress level (1-10)', type: 'number', required: true, min: 1, max: 10 },
      { name: 'anxietyLevel', label: 'Anxiety level (1-10)', type: 'number', required: true, min: 1, max: 10 },
      { name: 'depressionLevel', label: 'Depression level (1-10)', type: 'number', required: true, min: 1, max: 10 },
      { name: 'sleepQuality', label: 'Sleep quality (1-10)', type: 'number', required: true, min: 1, max: 10 },
      { name: 'energyLevel', label: 'Energy level (1-10)', type: 'number', required: true, min: 1, max: 10 },
      { name: 'overallStatus', label: 'Overall status', type: 'select', required: true, options: ['EXCELLENT', 'GOOD', 'FAIR', 'NEEDS_ATTENTION'] },
      { name: 'recommendations', label: 'Recommendations', type: 'textarea' },
      { name: 'nextAssessmentDate', label: 'Next assessment date', type: 'date', required: true },
    ],
  },
}

export const entityList = Object.values(entities)
